[platformio]
default_envs = esp32-s3-supermini

[env:esp32-s3-supermini]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
board_build.mcu = esp32s3
board_build.f_cpu = 160000000L
board_build.flash_mode = qio
board_build.partitions = huge_app.csv
board_upload.flash_size = 4MB
build_flags = 
    -DARDUINO_USB_CDC_ON_BOOT=1
    -DARDUINO_USB_MODE=1
    -DBOARD_HAS_PSRAM
    -mfix-esp32-psram-cache-issue
    -DENABLE_TAILSCALE=1
    -DCONFIG_ML_MAX_PEERS=32
    -DCONFIG_ML_NVS_MAX_PEERS=64
    -DWIREGUARD_MAX_PEERS=32
    -DCONFIG_ML_H2_BUFFER_SIZE_KB=256
    -DCONFIG_ML_JSON_BUFFER_SIZE_KB=256
    -DCONFIG_ML_PRIORITY_PEER_IP='""'
    -DCONFIG_ML_DEVICE_NAME='"jbd-bms-probe"'
    -DCONFIG_ML_TAILSCALE_AUTH_KEY='"tskey-auth-kKU7ahB6hj11CNTRL-EFJu3jE5VBTZjKuksJtxBT2ptmd2AuJ6"'
    -DCONFIG_ML_WIFI_SSID='""'
    -DCONFIG_ML_WIFI_PASSWORD='""'
    -DWIREGUARD_CRYPTO_REFC=1
    -Ilib/wireguard_lwip/src
    -Ilib/wireguard_lwip/src/crypto/refc
    -Ilib/microlink/include
    -Ilib/microlink/src
    -Wno-stringop-overread
    -DCORE_DEBUG_LEVEL=1
board_build.arduino.memory_type = qio_qspi
upload_port = /dev/cu.usbmodem3101
upload_speed = 921600
monitor_port = /dev/cu.usbmodem3101
monitor_speed = 115200
lib_deps = 
    h2zero/NimBLE-Arduino @ ^2.1.0
    bblanchon/ArduinoJson @ ^7.0.4
