/**
 * @file ml_config_html.h
 * @brief Embedded HTML/CSS/JS config page for MicroLink HTTP server
 *
 * Single-page dashboard with vanilla HTML + CSS + Fetch API.
 * Sections: Monitor, WiFi Networks, Peer Allowlist, Device Settings.
 */

#pragma once

static const char CONFIG_PAGE_HTML[] =
"<!DOCTYPE html>"
"<html><head><meta charset='utf-8'><meta name='viewport' content='width=device-width,initial-scale=1'>"
"<title>MicroLink</title>"
"<style>"
"*{box-sizing:border-box;margin:0;padding:0}"
"body{font-family:system-ui,-apple-system,sans-serif;background:#0d1117;color:#e6edf3;padding:0}"
".wrap{max-width:1100px;margin:0 auto;padding:20px}"

/* Header bar */
".hdr{background:#161b22;border-bottom:1px solid #30363d;padding:14px 20px;display:flex;"
"align-items:center;justify-content:space-between;flex-wrap:wrap;gap:10px}"
".hdr h1{font-size:1.4em;color:#58a6ff;font-weight:700}"
".hdr-right{display:flex;align-items:center;gap:12px}"
".conn-badge{padding:5px 12px;border-radius:12px;font-size:.8em;font-weight:600}"
".conn-wifi{background:#1f6feb30;color:#58a6ff;border:1px solid #1f6feb}"
".conn-cell{background:#da363330;color:#f85149;border:1px solid #da3633}"
".hdr-ip{font-family:monospace;font-size:1em;color:#58a6ff;font-weight:600}"
".hdr-host{color:#8b949e;font-size:.85em}"

/* Section cards */
".section{background:#161b22;border:1px solid #30363d;border-radius:8px;margin-bottom:16px;overflow:hidden}"
".section-hdr{padding:12px 16px;border-bottom:1px solid #30363d;display:flex;"
"align-items:center;justify-content:space-between}"
".section-hdr h2{font-size:1.05em;color:#e6edf3;font-weight:600}"
".section-body{padding:16px}"

/* Monitor grid */
".mon-grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(140px,1fr));gap:10px}"
".mon-card{background:#0d1117;padding:14px;border-radius:6px;border:1px solid #21262d}"
".mon-card .val{font-size:1.6em;color:#58a6ff;font-weight:700;line-height:1.2}"
".mon-card .lbl{font-size:.75em;color:#8b949e;margin-top:4px;text-transform:uppercase;letter-spacing:.5px}"
".task-list{margin-top:12px}"
".task-row{display:flex;justify-content:space-between;padding:8px 12px;background:#0d1117;"
"border-radius:4px;margin:4px 0;font-size:.85em;border:1px solid #21262d}"
".task-row .tn{color:#58a6ff;font-family:monospace;font-weight:600}"
".task-row .ts{color:#8b949e}"

/* Settings form */
".form-grid{display:grid;grid-template-columns:1fr 1fr;gap:12px 20px}"
"@media(max-width:640px){.form-grid{grid-template-columns:1fr}}"
".form-group{display:flex;flex-direction:column}"
".form-group.full{grid-column:1/-1}"
".form-group label{font-size:.8em;color:#8b949e;margin-bottom:4px;font-weight:500}"
".form-group .hint{font-size:.7em;color:#484f58;margin-top:2px}"
"input[type=text],input[type=password],input[type=number]{width:100%;padding:10px 12px;"
"background:#0d1117;border:1px solid #30363d;color:#e6edf3;border-radius:6px;font-size:.9em}"
"input:focus{border-color:#58a6ff;outline:none;box-shadow:0 0 0 2px #1f6feb40}"
"button{padding:10px 20px;border:none;border-radius:6px;cursor:pointer;font-size:.85em;"
"font-weight:600;transition:opacity .15s}"
"button:hover{opacity:.85}"
".btn-primary{background:#238636;color:#fff}"
".btn-danger{background:#da3633;color:#fff}"
".btn-sm{padding:6px 12px;font-size:.8em}"
".btn-add{background:#238636;color:#fff}"
".btn-outline{background:transparent;border:1px solid #30363d;color:#8b949e}"
".btn-outline:hover{border-color:#58a6ff;color:#58a6ff}"
".chk-grid{display:grid;grid-template-columns:1fr 1fr;gap:6px}"
".chk{display:flex;gap:8px;align-items:center;font-size:.85em;color:#8b949e}"
".chk input{width:auto;accent-color:#58a6ff}"
".form-actions{grid-column:1/-1;display:flex;gap:10px;margin-top:6px;align-items:center}"
".msg{padding:10px;border-radius:6px;margin-top:8px;font-size:.85em;display:none;grid-column:1/-1}"
".msg-ok{background:#23863620;color:#3fb950;display:block;border:1px solid #23863640}"
".msg-err{background:#da363320;color:#f85149;display:block;border:1px solid #da363340}"

/* Peer list */
".peer-item{display:flex;align-items:center;gap:10px;padding:10px 12px;background:#0d1117;"
"border-radius:6px;margin:4px 0;font-size:.9em;border:1px solid #21262d}"
".peer-item .ip{font-family:monospace;color:#58a6ff;font-weight:500;min-width:120px}"
".peer-item .name{color:#8b949e;flex:1;overflow:hidden;text-overflow:ellipsis;white-space:nowrap}"
".peer-item .path{font-size:.75em;font-weight:600;padding:3px 8px;border-radius:10px}"
".path-direct{background:#23863620;color:#3fb950;border:1px solid #23863640}"
".path-derp{background:#d2992020;color:#d29922;border:1px solid #d2992040}"
".badge-ok{background:#23863620;color:#3fb950;font-size:.75em;padding:3px 8px;border-radius:10px;"
"border:1px solid #23863640}"
".badge-blocked{background:#da363320;color:#f85149;font-size:.75em;padding:3px 8px;border-radius:10px;"
"border:1px solid #da363340}"
".add-form{display:flex;gap:8px;margin:10px 0;align-items:center}"
".add-form input{flex:1}"
".peer-list{margin:8px 0}"

/* WiFi list */
".wifi-item{display:flex;align-items:center;gap:8px;padding:10px 12px;background:#0d1117;"
"border-radius:6px;margin:4px 0;font-size:.9em;border:1px solid #21262d}"
".wifi-item .num{color:#484f58;font-weight:700;min-width:24px;text-align:center}"
".wifi-item .ssid{font-family:monospace;color:#58a6ff;font-weight:500;flex:1}"
".wifi-item .wpw{color:#8b949e;font-size:.85em}"
".wifi-btns{display:flex;gap:4px}"
".wifi-btns button{padding:4px 8px;font-size:.75em}"

/* Empty state */
".empty{color:#484f58;font-size:.9em;padding:20px;text-align:center}"

"</style></head><body>"

/* ---- Header ---- */
"<div class='hdr'>"
"<div><h1>MicroLink</h1>"
"<span class='hdr-host' id='hostName'></span></div>"
"<div class='hdr-right'>"
"<span class='conn-badge conn-wifi' id='connBadge'>WiFi</span>"
"<span class='hdr-ip' id='vpnIp'>--</span>"
"</div></div>"

"<div class='wrap'>"

/* ---- Monitor Section ---- */
"<div class='section'>"
"<div class='section-hdr'><h2>System Monitor</h2>"
"<span style='color:#8b949e;font-size:.75em' id='monAutoRefresh'>auto-refresh 3s</span></div>"
"<div class='section-body'>"
"<div class='mon-grid'>"
"<div class='mon-card'><div class='val' id='mTemp'>--</div><div class='lbl'>Temperature</div></div>"
"<div class='mon-card'><div class='val' id='mRssi'>--</div><div class='lbl'>Signal</div></div>"
"<div class='mon-card'><div class='val' id='mUptime'>--</div><div class='lbl'>Uptime</div></div>"
"<div class='mon-card'><div class='val' id='mHeap'>--</div><div class='lbl'>Free Heap</div></div>"
"<div class='mon-card'><div class='val' id='mPsram'>--</div><div class='lbl'>Free PSRAM</div></div>"
"<div class='mon-card'><div class='val' id='mMinHeap'>--</div><div class='lbl'>Min Heap</div></div>"
"<div class='mon-card'><div class='val' id='mDerp'>--</div><div class='lbl'>DERP Region</div></div>"
"<div class='mon-card'><div class='val' id='mPeers'>--</div><div class='lbl'>Peers</div></div>"
"</div>"
"<div class='task-list' id='mTasks'></div>"
"</div></div>"

/* ---- WiFi Networks Section ---- */
"<div class='section'>"
"<div class='section-hdr'><h2>WiFi Networks</h2>"
"<span style='color:#8b949e;font-size:.75em'>priority order &mdash; restart required</span></div>"
"<div class='section-body'>"
"<p style='font-size:.8em;color:#8b949e;margin-bottom:10px'>"
"Device tries each network in order until connected. Drag to reorder priority.</p>"
"<div id='wifiList'></div>"
"<div class='add-form'>"
"<input type='text' id='wifiSsid' placeholder='SSID'>"
"<input type='password' id='wifiPass' placeholder='Password'>"
"<button class='btn-add btn-sm' onclick='addWifi()'>Add</button>"
"</div>"
"<div class='msg' id='wifiMsg'></div>"
"</div></div>"

/* ---- Peers Section ---- */
"<div class='section'>"
"<div class='section-hdr'><h2>Peer Allowlist</h2>"
"<span style='color:#8b949e;font-size:.75em'>changes apply immediately</span></div>"
"<div class='section-body'>"
"<p style='font-size:.8em;color:#8b949e;margin-bottom:10px'>"
"Only allowed peers receive DISCO probes. Empty list = probe all peers.</p>"
"<div id='allowedList' class='peer-list'></div>"
"<div class='add-form'>"
"<input type='text' id='addIp' placeholder='100.x.y.z'>"
"<input type='text' id='addLabel' placeholder='label (optional)'>"
"<button class='btn-add btn-sm' onclick='addAllowed()'>Add</button>"
"</div>"
"<div class='msg' id='peersMsg'></div>"
"</div></div>"


/* ---- Settings Section ---- */
"<div class='section'>"
"<div class='section-hdr'><h2>Device Settings</h2>"
"<span style='color:#8b949e;font-size:.75em'>all changes require restart</span></div>"
"<div class='section-body'>"
"<div class='form-grid'>"

"<div class='form-group full'><label>Tailscale Auth Key</label>"
"<input type='password' id='auth_key' placeholder='tskey-auth-...'></div>"

"<div class='form-group'><label>Device Name Prefix</label>"
"<input type='text' id='device_prefix' placeholder='e.g. sensor'>"
"<div class='hint'>Auto-generates: prefix-MACID (e.g. sensor-a1b2c3)</div></div>"

"<div class='form-group'><label>Device Name (Full Override)</label>"
"<input type='text' id='device_name_full' placeholder='e.g. sensor-tailscale'>"
"<div class='hint'>Overrides prefix+MAC. DNS: name.tailnet.ts.net</div></div>"

"<div class='form-group'><label>Cellular APN</label>"
"<input type='text' id='cellular_apn'></div>"
"<div class='form-group'><label>SIM PIN</label>"
"<input type='password' id='cellular_sim_pin'></div>"
"<div class='form-group'><label>PPP Username</label>"
"<input type='text' id='ppp_user' placeholder='blank = none'></div>"
"<div class='form-group'><label>PPP Password</label>"
"<input type='password' id='ppp_pass' placeholder='blank = none'></div>"

/* Advanced */
"<div class='form-group full' style='margin-top:8px'>"
"<label style='color:#58a6ff;font-size:.85em;font-weight:600'>Advanced</label></div>"

"<div class='form-group'><label>Max Peers</label>"
"<input type='number' id='max_peers' min='0' max='64' placeholder='16 (default)'>"
"<div class='hint'>0 = use build default (16)</div></div>"

"<div class='form-group'><label>DISCO Heartbeat (ms)</label>"
"<input type='number' id='disco_heartbeat_ms' min='0' max='60000' placeholder='3000 (default)'>"
"<div class='hint'>0 = use default (3000ms)</div></div>"

"<div class='form-group'><label>Priority Peer IP</label>"
"<input type='text' id='priority_peer_ip' placeholder='100.x.y.z'></div>"

"<div class='form-group'><label>Control Plane Host</label>"
"<input type='text' id='ctrl_host' placeholder='Tailscale (default)'>"
"<div class='hint'>For Headscale/Ionscale. Empty = Tailscale</div></div>"

/* Debug */
"<div class='form-group full' style='margin-top:8px'>"
"<label style='color:#58a6ff;font-size:.85em;font-weight:600'>Debug Logging</label></div>"
"<div class='form-group full'><div class='chk-grid'>"
"<div class='chk'><input type='checkbox' id='dbg_disco'><label>DISCO</label></div>"
"<div class='chk'><input type='checkbox' id='dbg_wg'><label>WireGuard</label></div>"
"<div class='chk'><input type='checkbox' id='dbg_derp'><label>DERP</label></div>"
"<div class='chk'><input type='checkbox' id='dbg_coord'><label>Coordinator</label></div>"
"</div></div>"

"<div class='form-actions'>"
"<button class='btn-primary' onclick='saveSettings()'>Save Settings</button>"
"<button class='btn-danger' onclick='doRestart()'>Restart Device</button>"
"</div>"
"<div class='msg' id='settingsMsg'></div>"
"</div></div>"

"</div>"  /* .wrap */

/* ---- JavaScript ---- */
"<script>"
"let allowedPeers=[];"
"let wifiNetworks=[];"

"function showMsg(id,msg,ok){"
"const el=document.getElementById(id);"
"el.textContent=msg;"
"el.className='msg '+(ok?'msg-ok':'msg-err');"
"setTimeout(()=>{el.className='msg';},5000);"
"}"

"function fmtUptime(s){"
"var d=s/86400|0,h=(s%86400)/3600|0,m=(s%3600)/60|0;"
"if(d>0)return d+'d '+h+'h';"
"if(h>0)return h+'h '+m+'m';"
"return m+'m '+(s%60|0)+'s';"
"}"

/* ---- Status bar ---- */
"async function loadStatus(){"
"try{"
"const r=await fetch('/api/status');"
"const d=await r.json();"
"document.getElementById('vpnIp').textContent=d.vpn_ip||'--';"
"document.getElementById('hostName').textContent=d.hostname||'';"
"}catch(e){document.getElementById('vpnIp').textContent='offline';}"
"}"

/* ---- Monitor ---- */
"async function loadMonitor(){"
"try{"
"const r=await fetch('/api/monitor');"
"const d=await r.json();"
"document.getElementById('mTemp').textContent=d.temp_c!=null?d.temp_c+'\\u00b0C':'N/A';"
/* Signal: show RSSI for wifi, just 'Cellular' for cell */
"var sig='N/A';"
"if(d.connection==='cellular'){sig='Cellular';}else if(d.rssi!=null){sig=d.rssi+' dBm';}"
"document.getElementById('mRssi').textContent=sig;"
"document.getElementById('mUptime').textContent=fmtUptime(d.uptime_s);"
"document.getElementById('mHeap').textContent=(d.free_heap/1024|0)+' KB';"
"document.getElementById('mPsram').textContent=(d.free_psram/1024|0)+' KB';"
"document.getElementById('mMinHeap').textContent=(d.min_free_heap/1024|0)+' KB';"
"document.getElementById('mDerp').textContent=d.derp_home_region>0?"
"'#'+d.derp_home_region+(d.derp_connected?' (up)':' (down)'):'--';"
/* Connection badge */
"var cb=document.getElementById('connBadge');"
"if(d.connection==='cellular'){"
"cb.textContent='Cellular';cb.className='conn-badge conn-cell';"
"document.querySelector('.mon-card:nth-child(2) .lbl').textContent='Connection';"
"}else{"
"cb.textContent='WiFi';cb.className='conn-badge conn-wifi';"
"document.querySelector('.mon-card:nth-child(2) .lbl').textContent='WiFi RSSI';"
"}"
/* Peer count card */
"const sr=await fetch('/api/status');"
"const sd=await sr.json();"
"document.getElementById('mPeers').textContent=sd.peer_count||0;"
/* Task stacks */
"var te=document.getElementById('mTasks');"
"if(d.tasks){"
"te.innerHTML=Object.entries(d.tasks).map(([n,t])=>"
"'<div class=\"task-row\"><span class=\"tn\">'+n+'</span>"
"<span class=\"ts\">'+t.state+' | '+t.stack_free+' B free</span></div>'"
").join('');"
"}else{te.innerHTML='';}"
"}catch(e){}"
"}"

/* ---- Settings ---- */
"async function loadSettings(){"
"try{"
"const r=await fetch('/api/settings');"
"const d=await r.json();"
"document.getElementById('auth_key').value=d.auth_key||'';"
"document.getElementById('device_prefix').value=d.device_prefix||'';"
"document.getElementById('device_name_full').value=d.device_name_full||'';"
"document.getElementById('cellular_apn').value=d.cellular_apn||'';"
"document.getElementById('cellular_sim_pin').value=d.cellular_sim_pin||'';"
"document.getElementById('ppp_user').value=d.ppp_user||'';"
"document.getElementById('ppp_pass').value=d.ppp_pass||'';"
"var mp=d.max_peers||0;"
"document.getElementById('max_peers').value=mp>0?mp:'';"
"var hb=d.disco_heartbeat_ms||0;"
"document.getElementById('disco_heartbeat_ms').value=hb>0?hb:'';"
"document.getElementById('priority_peer_ip').value=d.priority_peer_ip||'';"
"document.getElementById('ctrl_host').value=d.ctrl_host||'';"
"var f=d.debug_flags||0;"
"document.getElementById('dbg_disco').checked=!!(f&1);"
"document.getElementById('dbg_wg').checked=!!(f&2);"
"document.getElementById('dbg_derp').checked=!!(f&4);"
"document.getElementById('dbg_coord').checked=!!(f&8);"
"}catch(e){}"
"}"

"async function saveSettings(){"
"var df=0;"
"if(document.getElementById('dbg_disco').checked)df|=1;"
"if(document.getElementById('dbg_wg').checked)df|=2;"
"if(document.getElementById('dbg_derp').checked)df|=4;"
"if(document.getElementById('dbg_coord').checked)df|=8;"
"const body={"
"auth_key:document.getElementById('auth_key').value,"
"device_prefix:document.getElementById('device_prefix').value,"
"device_name_full:document.getElementById('device_name_full').value,"
"cellular_apn:document.getElementById('cellular_apn').value,"
"cellular_sim_pin:document.getElementById('cellular_sim_pin').value,"
"ppp_user:document.getElementById('ppp_user').value,"
"ppp_pass:document.getElementById('ppp_pass').value,"
"max_peers:parseInt(document.getElementById('max_peers').value)||0,"
"disco_heartbeat_ms:parseInt(document.getElementById('disco_heartbeat_ms').value)||0,"
"priority_peer_ip:document.getElementById('priority_peer_ip').value,"
"ctrl_host:document.getElementById('ctrl_host').value,"
"debug_flags:df"
"};"
"try{"
"const r=await fetch('/api/settings',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});"
"const d=await r.json();"
"showMsg('settingsMsg','Saved. Restart device for changes to take effect.',true);"
"}catch(e){showMsg('settingsMsg','Save failed: '+e,false);}"
"}"

/* ---- WiFi Networks ---- */
"async function loadWifi(){"
"try{"
"const r=await fetch('/api/wifi');"
"const d=await r.json();"
"wifiNetworks=d.networks||[];"
"renderWifi();"
"}catch(e){}"
"}"

"function renderWifi(){"
"const el=document.getElementById('wifiList');"
"if(wifiNetworks.length===0){"
"el.innerHTML='<div class=\"empty\">No WiFi networks configured</div>';"
"return;}"
"el.innerHTML=wifiNetworks.map(function(w,i){"
"var h='<div class=\"wifi-item\">';"
"h+='<span class=\"num\">#'+(i+1)+'</span>';"
"h+='<span class=\"ssid\">'+w.ssid+'</span>';"
"h+='<span class=\"wpw\">'+w.pass+'</span>';"
"h+='<div class=\"wifi-btns\">';"
"if(i>0)h+='<button class=\"btn-outline btn-sm\" onclick=\"moveWifi('+i+',-1)\">\\u2191</button>';"
"if(i<wifiNetworks.length-1)h+='<button class=\"btn-outline btn-sm\" onclick=\"moveWifi('+i+',1)\">\\u2193</button>';"
"h+='<button class=\"btn-danger btn-sm\" onclick=\"removeWifi('+i+')\">\\u2715</button>';"
"h+='</div></div>';"
"return h;"
"}).join('');"
"}"

"function addWifi(){"
"const s=document.getElementById('wifiSsid').value.trim();"
"const p=document.getElementById('wifiPass').value;"
"if(!s){showMsg('wifiMsg','SSID required',false);return;}"
"if(wifiNetworks.length>=16){showMsg('wifiMsg','Max 16 networks',false);return;}"
"if(wifiNetworks.some(w=>w.ssid===s)){showMsg('wifiMsg','SSID already in list',false);return;}"
"wifiNetworks.push({ssid:s,pass:p});"
"document.getElementById('wifiSsid').value='';"
"document.getElementById('wifiPass').value='';"
"renderWifi();"
"saveWifi();"
"}"

"function removeWifi(idx){"
"wifiNetworks.splice(idx,1);"
"renderWifi();"
"saveWifi();"
"}"

"function moveWifi(idx,dir){"
"var ni=idx+dir;"
"if(ni<0||ni>=wifiNetworks.length)return;"
"var tmp=wifiNetworks[idx];"
"wifiNetworks[idx]=wifiNetworks[ni];"
"wifiNetworks[ni]=tmp;"
"renderWifi();"
"saveWifi();"
"}"

"async function saveWifi(){"
"try{"
"const r=await fetch('/api/wifi',{method:'POST',headers:{'Content-Type':'application/json'},"
"body:JSON.stringify({networks:wifiNetworks})});"
"const d=await r.json();"
"if(d.ok)showMsg('wifiMsg','Saved. Restart for changes to take effect.',true);"
"else showMsg('wifiMsg','Save failed',false);"
"}catch(e){showMsg('wifiMsg','Save failed: '+e,false);}"
"}"

/* ---- Peer Allowlist ---- */
"async function loadAllowed(){"
"try{"
"const r=await fetch('/api/peers/allowed');"
"const d=await r.json();"
"allowedPeers=d.peers||[];"
"renderAllowed();"
"}catch(e){}"
"}"

"function renderAllowed(){"
"const el=document.getElementById('allowedList');"
"if(allowedPeers.length===0){"
"el.innerHTML='<div class=\"empty\">No filter active &mdash; all peers will be probed</div>';"
"return;"
"}"
"el.innerHTML=allowedPeers.map((p,i)=>"
"'<div class=\"peer-item\">"
"<span class=\"ip\">'+p.ip+'</span>"
"<span class=\"name\">'+p.label+'</span>"
"<button class=\"btn-danger btn-sm\" onclick=\"removeAllowed('+i+')\">Remove</button>"
"</div>'"
").join('');"
"}"

"async function saveAllowed(){"
"try{"
"await fetch('/api/peers/allowed',{method:'POST',headers:{'Content-Type':'application/json'},"
"body:JSON.stringify({peers:allowedPeers})});"
"loadStatus();"
"showMsg('peersMsg','Allowlist updated',true);"
"}catch(e){showMsg('peersMsg','Save failed: '+e,false);}"
"}"

"function addAllowed(){"
"const ip=document.getElementById('addIp').value.trim();"
"const label=document.getElementById('addLabel').value.trim();"
"if(!ip)return;"
"if(allowedPeers.some(p=>p.ip===ip)){showMsg('peersMsg','Already in list',false);return;}"
"allowedPeers.push({ip:ip,label:label||ip});"
"document.getElementById('addIp').value='';"
"document.getElementById('addLabel').value='';"
"renderAllowed();"
"saveAllowed();"
"}"

"function removeAllowed(idx){"
"allowedPeers.splice(idx,1);"
"renderAllowed();"
"saveAllowed();"
"}"



/* ---- Restart ---- */
"async function doRestart(){"
"if(!confirm('Restart the device?'))return;"
"try{await fetch('/api/restart',{method:'POST'});}catch(e){}"
"document.getElementById('vpnIp').textContent='Restarting...';"
"}"

/* ---- Init ---- */
"loadStatus();loadWifi();loadSettings();loadAllowed();loadMonitor();"
"setInterval(loadStatus,5000);"
"setInterval(loadMonitor,3000);"
"</script></body></html>";
